// Generated by https://quicktype.io

export interface CreateChannelResponse {
  result: {
    $metadata: Metadata;
    channel: Channel;
    streamKey: StreamKey;
  };
}

export interface Metadata {
  httpStatusCode: number;
  requestId: string;
  cfId: string;
  attempts: number;
  totalRetryDelay: number;
}

export interface Channel {
  arn: string;
  authorized: boolean;
  ingestEndpoint: string;
  latencyMode: string;
  name: string;
  playbackUrl: string;
  recordingConfigurationArn: string;
  tags: Tags;
  type: string;
}

export interface Tags {}

export interface StreamKey {
  arn: string;
  channelArn: string;
  tags: Tags;
  value: string;
}
