// Generated by https://quicktype.io

export interface PushMetaDataResponse {
  result: Result;
}

export interface Result {
  $metadata: Metadata;
}

export interface Metadata {
  httpStatusCode: number;
  requestId: string;
  cfId: string;
  attempts: number;
  totalRetryDelay: number;
}
