import { MetaData } from '@src/types/share/TimeMetadataFormat';

// Generated by https://quicktype.io
import { Concert } from './Concert';

export interface Ticket {
  timeMetaData?: Array<MetaData>;
  streamKeyValue: string;
  streamKeyArn: string;
  saleStartDate: string;
  saleEndDate: string;
  runningTime: number;
  price: number;
  playbackUrl: string;
  ingestEndpoint: string;
  id: number;
  concertStartDate: string;
  concertId: number;
  concertEndDate: string;
  concert?: Concert;
  channelArn: string;
  archiveEndTime: string;
}
