import { MetaData } from "./../TimeMetadataFormat";
import { Concert } from "./Concert";
// Generated by https://quicktype.io

export interface Ticket {
  id: number;
  concertId: number;
  concert: Concert;
  price: number;
  runningTime: number;
  saleStartDate: string;
  saleEndDate: string;
  concertStartDate: string;
  concertEndDate: string;
  archiveEndTime: string;
  channelArn: string;
  playbackUrl: string;
  streamKeyArn: string;
  streamKeyValue: string;
  ingestEndpoint: string;
  timeMetaData?: Array<MetaData>;
}
